pipeline:
  ping:
    image: mongo:3.4.4
    commands:
      - sleep 15
      - mongo --host mongo

  install:
    image: goharbor.erxes.io/erxes/runner:latest
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install

  linting:
    image: node:8-slim
    commands:
      - yarn lint

  typescript:
    image: node:8-slim
    commands:
      - yarn tsc

  testing:
    image: node:8-slim
    environment:
      - TEST_MONGO_URL=mongodb://mongo/test
    commands:
      - yarn test
  publish:
    image: plugins/docker
    repo: goharbor.erxes.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    registry: goharbor.erxes.io
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - latest-${DRONE_COMMIT}

services:
  mongo:
      image: mongo:3.4.4
      command: [ --smallfiles ]
