pipeline:
  ping:
    image: mongo:3.4.4
    commands:
      - sleep 15
      - mongo --host mongo

  install:
    image: erxes/runner:latest
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install

  linting:
    image: erxes/runner:latest
    commands:
      - yarn lint

  typescript:
    image: erxes/runner:latest
    commands:
      - yarn tsc

  testing:
    image: erxes/runner:latest
    environment:
      - TEST_MONGO_URL=mongodb://mongo/test
    commands:
      - yarn test

  build:
    image: erxes/runner:latest
    commands:
      - yarn build
      - mkdir prod
      - cp -a dist prod
      - cp -a node_modules prod
      - cp package.json prod
      - cp .env.sample prod/.env

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_BRANCH}-latest

services:
  mongo:
    image: mongo:3.4.4
    command: [--smallfiles]
